---
title: "viz_part_01"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## lets import data'

```{r}
library(tidyverse)
library(ggridges)
library(viridis)

```




```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```


## scatterplot
but better

```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha=.5) +
  labs(
    x = "minimum Daily Temp (C)",
    y = "Maximum Daily Temp (C)",
    title = "Scatterplot of daily Temp",
    caption = "data came from the rnoaa package"
  ) +
  scale_x_continuous(
    breaks = c(-10, 0, 15),
    labels = c("-10", "0", "15")
  ) + scale_y_continuous(
    trans = "sqrt"
  )

```


```{r}
weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha=.5) +
  labs(
    x = "minimum Daily Temp (C)",
    y = "Maximum Daily Temp (C)",
    title = "Scatterplot of daily Temp",
    caption = "data came from the rnoaa package"
  ) +
  scale_color_hue(
    name = "location",
    h = c(100,300)
    )

```


```{r}
gg_weather = 
  weather_df %>% 
  ggplot(aes(x=tmin, y=tmax, color = name)) +
  geom_point(alpha=.5) +
  labs(
    x = "minimum Daily Temp (C)",
    y = "Maximum Daily Temp (C)",
    title = "Scatterplot of daily Temp",
    caption = "data came from the rnoaa package"
  ) +
  viridis::scale_color_viridis(
    name = "Location", 
    discrete = TRUE
  )
```


## Themes

```{r}
gg_weather +
  theme(legend.position = "bottom")
```


```{r}
gg_weather +
  theme_bw()



gg_weather +
  theme_minimal()


 gg_weather +
  theme_classic()
```




```{r}
gg_weather +
  theme_minimal() +
  theme(legend.position = "bottom") 


```


